#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-push checks..."

# Run lint and type-check
pnpm run lint && pnpm run type-check
status=$?
if [ $status -ne 0 ]; then
  echo "Lint or Type-check failed. Push aborted."
  exit $status
fi

exit 0
